vehiclesCount: 1              # valid value is from 1 to 100
maxSpeed: 1                   # valid value is from 1 to 200
maxTimeStep: 60s              # valid value is from 1s to 24h
cacheSize: 1000               # valid value is from 1 to 1 000 000
brokerHost: localhost:9092    # valid value has form host:port
topicName: topic1             # valid value is not empty string
grpsPort: 50051               # valid value is from 0 to 65536