version: '2'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      zookeeper:
        condition: service_started
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 9092:9092
    command:
      - sh
      - -c
      - |
        /etc/confluent/docker/run &
        PID=$!

        while ! nc -z localhost 9092; do sleep 1; done

        kafka-topics --create --topic topic1 --bootstrap-server localhost:9092 --partitions 1 --replication-factor 1

        wait $PID
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9092"]
      interval: 15s
      timeout: 5s
      retries: 3

  generator:
    build: .
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_BROKER: kafka:9092
    ports:
      - 50051:50051
